[build.targets.sdist]
include = [
  'src/',
]

[build.targets.wheel]
packages = [
  'src/pre_commit_no_emoji/',
]

[metadata.hooks.vcs.urls]
'Source Archive' = 'https://github.com/MaxymVlasov/pre-commit-no-emoji/archive/{commit_hash}.tar.gz'
'GitHub: repo' = 'https://github.com/MaxymVlasov/pre-commit-no-emoji'

[version]
source = 'vcs'
